id: AE5C38B4D
base_file: fCF76.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:13:18.177991
  last_modified_at: 2022-06-05 20:13:18.177997
